### ISSUE TITLE
get_permissions does not work

### ISSUE THREAD

**Issue by acd124** [chrisdewa/unbelipy#17]
### Summary

get_permissions always raises a type error

### Reproduction steps

1. Call the client.get_permissions method with a valid input

### Expected result

The code should run properly

### Actual result

line 239, in get_permissions
    bucket = method + path
TypeError: can only concatenate tuple (not "str") to tuple

### System information

No module named unbelipy.__main__; 'unbelipy' is a package and cannot be directly executed

### Checklist

- [X] I have searched the entire issue tracker, and have ensured this is not a duplicate.
- [X] I have removed any sensitive information, such as my Application Token, if visible.

**Comment by chrisdewa** [comment]
This should be fixed with commit [57bee80](https://github.com/chrisdewa/unbelipy/commit/57bee80ea8916de124a264e3ccce75bbcf6daabb).
