### ISSUE TITLE
Example code raises errors

### ISSUE THREAD

**Issue by acd124** [chrisdewa/unbelipy#19]
### Summary

Example code for get and set user balance throws errors

### Reproduction steps

1. Attempt to run the example code from the README

### Expected result

The code should run properly

### Actual result

ValueError: when cash is a str, it has to be "Infinity" but "5" was received
from both get_user_balance and set_user_balance

### System information

No module named unbelipy.__main__; 'unbelipy' is a package and cannot be directly executed

### Checklist

- [X] I have searched the entire issue tracker, and have ensured this is not a duplicate.
- [X] I have removed any sensitive information, such as my Application Token, if visible.

### Additional information

Just change the examples to use ints

**Comment by chrisdewa** [comment]
We're aware that the current version has some bugs, we're working on it, the version at the master branch of the repository is currently being developed to solve them. Thanks for the PR we'll resolve it when the new version is published.

**Comment by chrisdewa** [comment]
Fixed on commit #3aa5453

**Comment by acd124** [comment]
The README.md example has not been updated.

**Comment by chrisdewa** [comment]
I just did in commit [b0e89f0](https://github.com/chrisdewa/unbelipy/commit/b0e89f01e38d17e3dd2c98f0b23e55b34e523935). I only noticed one thing that needed to be changed, the `member_id` variable's name. If there's something else please tell me.

**Comment by acd124** [comment]
The issue I had s as mentioned in the actual result is that the example has the amount as a string instead of a number.

**Comment by chrisdewa** [comment]
You're right, I missed that, but it's fixed now, thanks
