### ISSUE TITLE
UnbeliClient.rate_limit_data is irrelevent

### ISSUE THREAD

**Issue by acd124** [chrisdewa/unbelipy#2]
Running requests to different routes overwrites the current rate_limit_data, leaving no indication which route it was for

**Comment by chrisdewa** [comment]
Thanks for the input. I still need to add buckets for the different routes. I'll solve the issue when I'm done.

**Comment by chrisdewa** [comment]
I rewrote rate_limit_data to hold a lot more information to be updated after each request. Please review changes, most of which happened in a new file `unbelipy.rate_limits`

**Comment by acd124** [comment]
getting a user balance from 2 different guilds will still overwrite the first one's rate limit data

**Comment by chrisdewa** [comment]
Yes, it's handled in a "per bucket" fashion. I don't think it would be useful to keep the information for every request ever made. What could be done is add logging.

Or what do you suggest?

**Comment by acd124** [comment]
I would recommend looking at [https://github.com/UnbelievaBoat/unb-api/blob/master/src/lib/RequestHandler.js](https://github.com/UnbelievaBoat/unb-api/blob/master/src/lib/RequestHandler.js) for how rate limits are handled. If you look at the parser for getting the route, it parses the method, like GET, and keeps the guild id, but does not care about the user id.

**Comment by chrisdewa** [comment]
I'm reviewing the subject and while I'm not sure If it's actually resolved i reopened it.

**Comment by chrisdewa** [comment]
recent commit now allows the client to handle the requests to prevent 429. As it still needs tuning setting UnbClient(TOKEN, prevent_rate_limits=False) makes the client ignore this mechanic. Request errors can be handled by excepting the errors under unbelipy.errors.

**Comment by chrisdewa** [comment]
@acd124 last commit (version 0.0.9a) should finish addressing rate limits. If you're willing i'd appreciate the feedback.
