### ISSUE TITLE
unbelipy references a dependency which it does not list as a dependency

### ISSUE THREAD

**Issue by acd124** [chrisdewa/unbelipy#3]
Since I was testing on repl.it, aiohttp was autmatically installed as a dependency to my project, however aiolimiter was not automatically found and installed, so it errored. This may cause more issues for people running a bot on their own machine rather than on a site like repl.it which takes care of a lot of checks for you. Listing the packages as devDependencies is simply wrong, and breaks the package in any production environment.

**Comment by chrisdewa** [comment]
I personally corroborated that the fix is effective on repl.it
