### ISSUE TITLE
Known issues issue

### ISSUE THREAD

**Issue by acd124** [chrisdewa/unbelipy#4]
1. -Infinity: There are bugs with this, if you want to include it under known bugs, say that it is an issue with the api itself if that's the truth. If that's the truth, bring it up in the api support channel in the Unbelievaboat support server. I believe specifying both cash and bank is a way to prevent it from bugging, but that doesn't mean the bug doesn't exist.
2. 404 errors: first off, get a spellchecker, secondly, if you're having issues with the api, bring it up in the api support channel in the support server, they'll try to work through the issue with you or the developer will look at it if necessary.

**Comment by chrisdewa** [comment]
I'll look into it. Thanks for pointing it up. I brought this issues to the support server. I'll update when i have more info. For the time being i'll leave the issue open.

**Comment by chrisdewa** [comment]
Devs have corroborated both situations. I'll update the readme appropriately.

**Comment by acd124** [comment]
`client.edit_balace` is misspelled

**Comment by chrisdewa** [comment]
closed. Dev answered the questions. Infinity issue has to do with how null (-Infinity) is managed by the API and the random 404 was a temporary issue now solved
