### ISSUE TITLE
Balance string representation lacks information

### ISSUE THREAD

**Issue by acd124** [chrisdewa/unbelipy#5]
Representing a balance by just showing the total amount leaves out important information. The balance is more accurately represented as a cash portion and a bank portion, since the total can be calculated by adding, whereas the opposite cannot. You can still put the total in the string representation, but leaving out the cash and bank makes it much harder to distinguish between someone with 500 cash or 500 bank, or -2000 cash and 2500 bank.

**Comment by chrisdewa** [comment]
Alright, initially i removed this information because it seemed unnecessarily long, but i understand your point so i added the info with commit a4a432a .
